language: r

warnings_are_errors: true

cache: packages

sudo: required

before_install:
  - "curl -s http://archive.cloudera.com/cdh4/ubuntu/precise/amd64/cdh/archive.key | sudo apt-key add -"
  - "wget http://archive.cloudera.com/cdh4/one-click-install/precise/amd64/cdh4-repository_1.0_all.deb"
  - "sudo dpkg -i cdh4-repository_1.0_all.deb"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y zookeeper-server"
  - "curl -o apache-drill-1.10.0.tar.gz http://apache.mirrors.hoobly.com/drill/drill-1.10.0/apache-drill-1.10.0.tar.gz"
  - "sudo mkdir $HOME/local"
  - "sudo chmod 777 $HOME/local"
  - "tar -xvzf apache-drill-1.10.0.tar.gz -C $HOME/local"

before_script:
  - "sudo service zookeeper-server init"
  - "sudo service zookeeper-server start"
  - "$HOME/local/apache-drill-1.10.0/bin/drillbit.sh start"
  - "sleep 5"

after_script:
  - "$HOME/local/apache-drill-1.10.0/bin/drillbit.sh stop"
  - "sudo service zookeeper-server stop"

after_success:
  - Rscript -e 'covr::codecov()'

r:
 - oldrel
 - release

notifications:
  email:
    - bob@rud.is
