language: r

warnings_are_errors: true

cache: packages

sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-set-default

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install zookeeperd"
  - "curl -o apache-drill-1.13.0.tar.gz http://apache.mirrors.hoobly.com/drill/drill-1.13.0/apache-drill-1.13.0.tar.gz"
  - "sudo mkdir $HOME/local"
  - "sudo chmod 777 $HOME/local"
  - "tar -xvzf apache-drill-1.13.0.tar.gz -C $HOME/local"

before_script:
  - "$HOME/local/apache-drill-1.13.0/bin/drillbit.sh start"
  - "sleep 5"

after_success:
  - Rscript -e 'covr::codecov()'

r:
 - oldrel
 - release

notifications:
  email:
    - bob@rud.is
